region: test
dcs:
- test-dc
type: WebService
size: nano
network: host
instances: 1
env:
    OTP_SECRET: "SOME-PROD-SECRET"
    HOMEBANK_OAUTH: "HOMEBANK-OAUTH-LINK"
    OAUTH_GRANT_TYPE: "OAUTH-GRANT-TYPE"
    OAUTH_CLIENT_ID: "CLIENT-ID"
    OAUTH_CLIENT_SECRET: "CLIENT-SECRET"
    UCS_SERVICE: "UCS-SERVICE-URL"
    DATABASE_NAME: "DB-NAME"
    DATABASE_HOST: "DB-HOST"
    DATABASE_PORT: "DB-PORT"
    DATABASE_USERNAME: "DB-USERNAME"
    DATABASE_PASSWORD: "DB-PASS"
    ELASTIC_HOST: "ELASTIC-HOST"